/**
 * Conversation Memory — persists session summaries to Supabase
 * so the AI tutor can reference prior conversations.
 *
 * Uses the `conversation_sessions` table:
 *   (id, user_id, summary, topic, message_count, created_at)
 *
 * Summaries are generated by sending the conversation to the AI
 * and asking for a 2-3 sentence recap of what was practiced.
 */

import { supabase } from './supabase';
import { chat } from './aiClient';
import type { ChatMessage } from './aiClient';

/**
 * Ask the AI to summarize a conversation into 2-3 sentences.
 * This runs through the same ai-chat edge function.
 */
async function generateSummary(
  messages: { role: string; content: string }[]
): Promise<string> {
  // Filter to user/assistant messages only (skip system prompt)
  const dialogue = messages
    .filter((m) => m.role === 'user' || m.role === 'assistant')
    .map((m) => `${m.role === 'user' ? 'Student' : 'Marie'}: ${m.content}`)
    .join('\n');

  const summaryMessages: ChatMessage[] = [
    {
      role: 'system',
      content:
        'You are a helpful assistant. Summarize the following French tutoring conversation in 2-3 English sentences. Focus on: what topics were discussed, what grammar/vocabulary was practiced, and what mistakes the student made. Be specific about verb tenses and vocabulary.',
    },
    {
      role: 'user',
      content: dialogue,
    },
  ];

  return chat(summaryMessages, { max_tokens: 150, temperature: 0.3 });
}

/**
 * Save a conversation summary after the session ends.
 * Only saves if there were at least 4 exchanges (2 user + 2 assistant).
 */
export async function saveConversationSummary(
  userId: string,
  messages: { role: string; content: string }[],
  topic?: string | null
): Promise<void> {
  if (!supabase) return;

  const userMessages = messages.filter((m) => m.role === 'user');
  if (userMessages.length < 2) return; // Not enough conversation to summarize

  try {
    const summary = await generateSummary(messages);

    await supabase.from('conversation_sessions').insert({
      user_id: userId,
      summary,
      topic: topic ?? null,
      message_count: messages.filter((m) => m.role !== 'system').length,
    });
  } catch (err) {
    console.error('Failed to save conversation summary:', err);
  }
}

/**
 * Fetch the N most recent conversation summaries for a user.
 * Used to inject context into the AI tutor's system prompt.
 */
export async function getRecentSummaries(
  userId: string,
  limit = 3
): Promise<string[]> {
  if (!supabase) return [];

  try {
    const { data, error } = await supabase
      .from('conversation_sessions')
      .select('summary')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })
      .limit(limit);

    if (error || !data) return [];
    return data.map((row) => row.summary).filter(Boolean);
  } catch {
    return [];
  }
}
